import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";

import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    const user = session?.user || null;
    const isLoggedIn = !!user;
    if (!isLoggedIn) redirect("/login");
    const { name } = user;
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header session={name} />
                <Provider>
                    {children}

                    <Toaster
                        position="top-center"
                        reverseOrder={false}
                        gutter={8}
                        containerClassName=""
                        containerStyle={{}}
                        toastOptions={{
                            // Define default options
                            className: "",
                            duration: 5000,
                            style: {
                                background: "#363636",
                                color: "#fff",
                            },
                        }}
                    />
                </Provider>
            </body>
        </html>
    );
}
